---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: activityapifoo
  namespace: activityapifoo
  labels:
    app: activityapifoo
spec:
  replicas: 3
  revisionHistoryLimit: 5
  template:
    metadata:
      name: activityapifoo
      labels:
        app: activityapifoo
        tier: web
    spec:
      containers:
        - name: activityapifoo
          image: eu.gcr.io/k8s-workshop-211107/activityapi:1c54953
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: environment-variables
          ports:
          - name: web
            containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5

